#!/bin/bash

JAVA_HOME="/usr/jdk/instances/java1.7.0"


##################
# PATH
##################
PATH=$PATH:${JAVA_HOME}/bin

##################
# CLASSPATH
##################
CLASSPATH=/opt/sw/certificate/lib/certificate.jar
CLASSPATH=${CLASSPATH}:/opt/sw/certificate/lib/certificate.jar

#mysql jars
CLASSPATH=${CLASSPATH}:/opt/sw/certificate/lib/mysql-connector-java-5.1.22-bin.jar

#derby jars
CLASSPATH=${CLASSPATH}:/opt/sw/certificate/lib/derby.jar
CLASSPATH=${CLASSPATH}:/opt/sw/certificate/lib/derbynet.jar

#Bouncycastle jars
CLASSPATH=${CLASSPATH}:/opt/sw/certificate/lib/bcprov-jdk15.jar

#Hibernate jars
CLASSPATH=${CLASSPATH}:/opt/sw/certificate/lib/hibernate-core-4.3.7.Final.jar
CLASSPATH=${CLASSPATH}:/opt/sw/certificate/lib/hibernate-entitymanager-4.3.7.Final.jar
CLASSPATH=${CLASSPATH}:/opt/sw/certificate/lib/hibernate-jpa-2.1-api-1.0.0.Final.jar
CLASSPATH=${CLASSPATH}:/opt/sw/certificate/lib/hibernate-commons-annotations-4.0.5.Final.jar
CLASSPATH=${CLASSPATH}:/opt/sw/certificate/lib/jboss-logging-3.1.3.GA.jar
CLASSPATH=${CLASSPATH}:/opt/sw/certificate/lib/jboss-logging-annotations-1.2.0.Beta1.jar
CLASSPATH=${CLASSPATH}:/opt/sw/certificate/lib/jboss-transaction-api_1.2_spec-1.0.0.Final.jar
CLASSPATH=${CLASSPATH}:/opt/sw/certificate/lib/xml-apis-1.0.b2.jar
CLASSPATH=${CLASSPATH}:/opt/sw/certificate/lib/dom4j-1.6.1.jar
CLASSPATH=${CLASSPATH}:/opt/sw/certificate/lib/antlr-2.7.7.jar
CLASSPATH=${CLASSPATH}:/opt/sw/certificate/lib/jandex-1.1.0.Final

##################
# JAVAFLAGS
##################
JAVAFLAGS="`echo ${JAVAFLAGS} | sed -e 's/\"//g'`"
JAVAFLAGS="${JAVAFLAGS} -Xmx256m"
JAVAFLAGS="${JAVAFLAGS} -Djava.util.logging.config.file"



##################
# REMOTEDEBUG
##################
REMOTEDEBUG_S="-Xdebug -Xrunjdwp:transport=dt_socket,address=8002,server=y,suspend=y"
REMOTEDEBUG_NS="-Xdebug -Xrunjdwp:transport=dt_socket,address=8002,server=y,suspend=n"
##################


# Set umask for able to write log for different users into the same log file
umask -S 0777

##################
# MAIN class
##################
if [ -z "${MAIN}" ]; then
  case "`basename $0`" in
    certAdmin)
    	MAIN=org.sumnata.cli.certAdmin	
    	 #JAVAFLAGS="$REMOTEDEBUG_S $JAVAFLAGS"
    	;;
    *) echo "Could not determine MAIN class" >&2; exit 2
  esac
fi

##################
# Launch
##################
exec "${JAVA_HOME}/bin/java" -cp "${CLASSPATH}" ${JAVAFLAGS} "${MAIN}" ${ARG} "$@"
